export interface RichSkill {
  id: string;
  name: string;
  shortName: string;
  fullName: string;
  marqueeName?: string;
  subname: string;
  category: "Front-End" | "Backend & DB" | "DevOps & Tooling" | "AI & Autonomous Tooling";
  brandColor: string;
  glowColor: string;
  tag: string;
  badgeStyle: string;
  logoUrl?: string;
  iconType: string;
  experience: string;
  proficiency: number;
  highlights: string[];
  benchmark: string;
  stackTier: "Frontend Layer" | "Core Backend & Data" | "Infrastructure & Runtime" | "AI Intelligence";
  inShowroomCard?: boolean; // Controls display in category cards in Design 3
}

export const SKILL_CATEGORIES = [
  "All",
  "Front-End",
  "Backend & DB",
  "DevOps & Tooling",
  "AI & Autonomous Tooling",
] as const;

export type SkillCategoryType = (typeof SKILL_CATEGORIES)[number];

export const RICH_SKILLS: RichSkill[] = [
  // ==========================================
  // 1. FRONT-END
  // ==========================================
  {
    id: "vue",
    name: "Vue.js",
    shortName: "Vue.js",
    fullName: "Vue.js (Vue 2 & Vue 3)",
    marqueeName: "Vue.js",
    subname: "Composition & Options API, Pinia, Vue Router & Vite",
    category: "Front-End",
    brandColor: "#42B883",
    glowColor: "rgba(66, 184, 131, 0.35)",
    tag: "Primary Framework",
    badgeStyle: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
    logoUrl: "/assets/img/logo/vuejs.png",
    iconType: "vue",
    experience: "4+ Years",
    proficiency: 96,
    highlights: [
      "Reactive enterprise single-page applications with smooth route transitions",
      "Pinia centralized state architecture & custom composable hooks",
      "Production migration of legacy Vue 2 options codebase to Vue 3 composition",
    ],
    benchmark: "Client portals with sub-second reactive state updates",
    stackTier: "Frontend Layer",
    inShowroomCard: true,
  },
  {
    id: "react-next",
    name: "React.js & Next.js",
    shortName: "React / Next",
    fullName: "React.js & Next.js",
    marqueeName: "React / Next.js",
    subname: "TypeScript, Custom Hooks, App Router & Tailwind CSS",
    category: "Front-End",
    brandColor: "#61DAFB",
    glowColor: "rgba(97, 218, 251, 0.35)",
    tag: "Modern Reactive UI",
    badgeStyle: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    logoUrl: "/assets/img/logo/react.png",
    iconType: "react",
    experience: "3+ Years",
    proficiency: 91,
    highlights: [
      "Component-driven design systems with strict TypeScript validation",
      "Next.js App Router for optimized static generation & SSR",
      "Interactive data dashboards with Framer Motion animations",
    ],
    benchmark: "High-impact interactive interfaces & enterprise portals",
    stackTier: "Frontend Layer",
    inShowroomCard: true,
  },
  {
    id: "vite",
    name: "Vite",
    shortName: "Vite",
    fullName: "Vite (Next-Gen Tooling)",
    marqueeName: "Vite",
    subname: "Next-Gen Frontend Tooling, Instant HMR & Rollup Bundling",
    category: "Front-End",
    brandColor: "#BD34FE",
    glowColor: "rgba(189, 52, 254, 0.4)",
    tag: "Build Tool",
    badgeStyle: "bg-purple-500/15 text-purple-300 border-purple-500/30",
    iconType: "vite",
    experience: "3+ Years",
    proficiency: 95,
    highlights: [
      "Sub-millisecond Hot Module Replacement (HMR) accelerating UI iteration",
      "Optimized production asset bundling with tree-shaking & code splitting",
      "Native ES module dev server configuration with multi-framework plugins",
    ],
    benchmark: "Instant local server startup & ultra-fast build pipelines",
    stackTier: "Frontend Layer",
    inShowroomCard: true,
  },
  {
    id: "npm",
    name: "NPM",
    shortName: "NPM",
    fullName: "NPM (Package Manager)",
    marqueeName: "NPM",
    subname: "Node Package Manager, Semantic Versioning & Dependency Resolution",
    category: "Front-End",
    brandColor: "#CB3837",
    glowColor: "rgba(203, 56, 55, 0.4)",
    tag: "Package Manager",
    badgeStyle: "bg-red-500/15 text-red-300 border-red-500/30",
    iconType: "npm",
    experience: "4+ Years",
    proficiency: 96,
    highlights: [
      "Dependency lockfile consistency & security audit vulnerability patching",
      "Custom build & deployment script automation in package.json workflows",
      "Scoped registry package configuration and monorepo workspaces",
    ],
    benchmark: "Standardized package resolution across fullstack repositories",
    stackTier: "Frontend Layer",
    inShowroomCard: true,
  },
  {
    id: "pnpm",
    name: "PNPM",
    shortName: "PNPM",
    fullName: "PNPM (Fast Package Manager)",
    marqueeName: "PNPM",
    subname: "Fast, Disk Space Efficient Package Manager with Content-Addressable Storage",
    category: "Front-End",
    brandColor: "#F69220",
    glowColor: "rgba(246, 146, 32, 0.4)",
    tag: "Fast Package Manager",
    badgeStyle: "bg-amber-500/15 text-amber-300 border-amber-500/30",
    iconType: "pnpm",
    experience: "2+ Years",
    proficiency: 92,
    highlights: [
      "Hard link sharing saving gigabytes of disk storage across monorepos",
      "Strict non-flat node_modules structure eliminating phantom dependencies",
      "Up to 2x faster installation benchmarks compared to conventional managers",
    ],
    benchmark: "Zero-duplicate dependency storage & rapid CI install pipelines",
    stackTier: "Frontend Layer",
    inShowroomCard: true,
  },
  {
    id: "blade-jquery",
    name: "Laravel Blade",
    shortName: "Laravel Blade",
    fullName: "Laravel Blade + Modern AJAX",
    marqueeName: "Laravel Blade",
    subname: "SPA-Alike Interactivity, Reactive Drawers, Dynamic Modals",
    category: "Front-End",
    brandColor: "#FF2D20",
    glowColor: "rgba(255, 45, 32, 0.35)",
    tag: "SPA-Alike",
    badgeStyle: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    logoUrl: "/assets/img/logo/laravel_logo.png",
    iconType: "blade",
    experience: "4+ Years",
    proficiency: 98,
    highlights: [
      "Turbo-charged server-rendered views with zero heavy client bundling lag",
      "Snappy asynchronous AJAX modals and sliding offcanvas drawers",
      "Modular Blade layout components with clean slot inheritance",
    ],
    benchmark: "Zero-latency server templates with snappy client interactions",
    stackTier: "Frontend Layer",
    inShowroomCard: false, // Stay in iconic moving box marquee, but removed from card
  },

  // ==========================================
  // 2. BACKEND & DB
  // ==========================================
  {
    id: "laravel-backend",
    name: "Laravel Framework",
    shortName: "Laravel",
    fullName: "Laravel Framework (v5 - v13)",
    marqueeName: "Laravel",
    subname: "PHP 8.3, Enterprise REST APIs & Service-Repository Architecture",
    category: "Backend & DB",
    brandColor: "#FF2D20",
    glowColor: "rgba(255, 45, 32, 0.4)",
    tag: "Core Mastery",
    badgeStyle: "bg-red-500/15 text-red-400 border-red-500/30",
    logoUrl: "/assets/img/logo/Laravel.svg",
    iconType: "laravel",
    experience: "4+ Years",
    proficiency: 99,
    highlights: [
      "Enterprise RESTful API design with policy gates & Spatie multi-role security",
      "Background job queues, event-driven listeners & scheduled workers",
      "Multi-tenant data isolation and clean service-repository design",
    ],
    benchmark: "Core backbone across 7+ live enterprise client platforms",
    stackTier: "Core Backend & Data",
    inShowroomCard: true,
  },
  {
    id: "nodejs",
    name: "Node.js",
    shortName: "Node.js",
    fullName: "Node.js (High-Throughput Runtime)",
    marqueeName: "Node.js",
    subname: "High-Throughput Asynchronous Event-Driven Runtime & REST APIs",
    category: "Backend & DB",
    brandColor: "#5FA04E",
    glowColor: "rgba(95, 160, 78, 0.4)",
    tag: "Async Runtime",
    badgeStyle: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30",
    logoUrl: "/assets/img/logo/nodejs.png",
    iconType: "nodejs",
    experience: "4+ Years",
    proficiency: 93,
    highlights: [
      "Non-blocking asynchronous I/O and event loop architecture",
      "Express.js & microservices handling concurrent client payloads",
      "Background daemon workers & real-time webhook listeners",
    ],
    benchmark: "Concurrent async microservices & high-speed event handlers",
    stackTier: "Core Backend & Data",
    inShowroomCard: true,
  },
  {
    id: "latex-pipeline",
    name: "LaTeX Engine",
    shortName: "LaTeX",
    fullName: "LaTeX (1,000+ pgs/sec Pipeline)",
    marqueeName: "LaTeX Engine",
    subname: "Asynchronous Queue Engine, Custom Packages & Dynamic Templates",
    category: "Backend & DB",
    brandColor: "#06B6D4",
    glowColor: "rgba(6, 182, 212, 0.4)",
    tag: "1,000+ pgs/sec",
    badgeStyle: "bg-teal-500/15 text-teal-300 border-teal-500/30",
    iconType: "latex",
    experience: "2+ Years",
    proficiency: 95,
    highlights: [
      "Asynchronous headless LaTeX compilation daemon surpassing DOM parsers by 800%",
      "Vector-perfect financial typography with embedded dynamic barcodes & seals",
      "Zero-leak memory worker pools handling continuous enterprise print streams",
    ],
    benchmark: "Compiles 1,000+ custom PDF invoice pages in seconds at IMT Tech",
    stackTier: "Core Backend & Data",
    inShowroomCard: true,
  },
  {
    id: "mysql",
    name: "MySQL Database",
    shortName: "MySQL",
    fullName: "MySQL Database (B-Tree Indexing)",
    marqueeName: "MySQL",
    subname: "Relational Engine, Composite B-Tree Indexing & ACID Transactions",
    category: "Backend & DB",
    brandColor: "#00758F",
    glowColor: "rgba(0, 117, 143, 0.4)",
    tag: "Relational DB",
    badgeStyle: "bg-blue-500/15 text-blue-300 border-blue-500/30",
    logoUrl: "/assets/img/logo/mysql.svg",
    iconType: "mysql",
    experience: "4+ Years",
    proficiency: 95,
    highlights: [
      "Composite index tuning slashing query latency by 40% on heavy transaction tables",
      "Optimistic locking algorithms preventing collision across 300+ room reservations",
      "Multi-tenant schema design with foreign key constraints & query explain plans",
    ],
    benchmark: "Sub-100ms aggregation queries across 10,000+ financial records",
    stackTier: "Core Backend & Data",
    inShowroomCard: true,
  },
  {
    id: "clickhouse",
    name: "ClickHouse Analytics",
    shortName: "ClickHouse",
    fullName: "ClickHouse Analytics (Columnar DBMS)",
    marqueeName: "ClickHouse",
    subname: "Column-Oriented High-Performance DBMS for Real-Time Analytical Aggregation",
    category: "Backend & DB",
    brandColor: "#FFCC00",
    glowColor: "rgba(255, 204, 0, 0.4)",
    tag: "Columnar Analytics",
    badgeStyle: "bg-yellow-500/15 text-yellow-300 border-yellow-500/30",
    iconType: "clickhouse",
    experience: "2+ Years",
    proficiency: 90,
    highlights: [
      "Columnar storage compression executing analytical queries 100x faster than traditional RDBMS",
      "Real-time event analytics and log aggregation pipelines",
      "High-throughput bulk data insertion with vectorized query execution",
    ],
    benchmark: "Sub-second rollups across massive event tables",
    stackTier: "Core Backend & Data",
    inShowroomCard: true,
  },
  {
    id: "postgres-sqlite",
    name: "PostgreSQL & SQLite",
    shortName: "PostgreSQL",
    fullName: "PostgreSQL & SQLite",
    marqueeName: "PostgreSQL",
    subname: "ACID Compliance, Embedded & Advanced Relational Features",
    category: "Backend & DB",
    brandColor: "#3B82F6",
    glowColor: "rgba(59, 130, 246, 0.35)",
    tag: "Relational & Embedded",
    badgeStyle: "bg-sky-500/15 text-sky-300 border-sky-500/30",
    iconType: "mysql",
    experience: "4+ Years",
    proficiency: 92,
    highlights: [
      "PostgreSQL JSONB queries and advanced relational constraints",
      "Zero-configuration SQLite embedded databases for lightning test suites",
      "Database migration scripts with rollback safeguards",
    ],
    benchmark: "Reliable transactional persistence across microservices",
    stackTier: "Core Backend & Data",
    inShowroomCard: true,
  },
  {
    id: "redis-valkey",
    name: "Redis & Valkey",
    shortName: "Redis",
    fullName: "Redis & Valkey (In-Memory Engine)",
    marqueeName: "Redis / Valkey",
    subname: "In-Memory Caching, Distributed Queues, Pub/Sub & Rate Limiting",
    category: "Backend & DB",
    brandColor: "#EF4444",
    glowColor: "rgba(239, 68, 68, 0.4)",
    tag: "In-Memory & Cache",
    badgeStyle: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    iconType: "redis",
    experience: "3+ Years",
    proficiency: 93,
    highlights: [
      "Sub-millisecond cache lookups for session states & frequent API queries",
      "Redis queue worker pools driving asynchronous background PDF rendering",
      "Distributed locks and sliding window rate limiting for public endpoints",
    ],
    benchmark: "High-throughput asynchronous job pipelines with zero backlog lag",
    stackTier: "Core Backend & Data",
    inShowroomCard: true,
  },
  {
    id: "nosql-mongo",
    name: "MongoDB",
    shortName: "MongoDB",
    fullName: "MongoDB & Google Firestore",
    marqueeName: "MongoDB",
    subname: "NoSQL Flexible Schemas, Aggregation Pipelines & Real-Time Streams",
    category: "Backend & DB",
    brandColor: "#10B981",
    glowColor: "rgba(16, 185, 129, 0.35)",
    tag: "NoSQL",
    badgeStyle: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
    logoUrl: "/assets/img/logo/mongo.png",
    iconType: "mongodb",
    experience: "3+ Years",
    proficiency: 89,
    highlights: [
      "Flexible document modeling and complex aggregation pipelines",
      "MERN stack lead acquisition platform handling active sales pipelines",
      "Real-time change stream listeners syncing client states instantaneously",
    ],
    benchmark: "Processed 1,000+ enterprise leads during Leadmind tenure",
    stackTier: "Core Backend & Data",
    inShowroomCard: false, // Stay in iconic moving box marquee, but removed from card
  },

  // ==========================================
  // 3. DEVOPS & RUNTIME INFRA
  // ==========================================
  {
    id: "gitlab-devsecops",
    name: "Gitlab DevSecOps",
    shortName: "GitLab",
    fullName: "Gitlab DevSecOps (CI/CD, Duo, Orbit)",
    marqueeName: "Gitlab DevSecOps (CI/CD, Duo, Orbit)",
    subname: "Automated CI/CD Pipelines, DevSecOps Security Audits, GitLab Duo & Orbit",
    category: "DevOps & Tooling",
    brandColor: "#FC6D26",
    glowColor: "rgba(252, 109, 38, 0.4)",
    tag: "CI/CD & Security",
    badgeStyle: "bg-orange-500/15 text-orange-300 border-orange-500/30",
    iconType: "gitlab",
    experience: "3+ Years",
    proficiency: 94,
    highlights: [
      "GitLab CI/CD multi-stage test, build, and zero-downtime deployment pipelines",
      "Automated SAST/DAST container vulnerability scanning & DevSecOps security gates",
      "GitLab Duo AI pair-assisted workflow & Orbit community telemetry",
    ],
    benchmark: "Automated test-to-deploy pipelines with zero manual friction",
    stackTier: "Infrastructure & Runtime",
    inShowroomCard: true,
  },
  {
    id: "git-versioning",
    name: "Git & GitHub Desktop",
    shortName: "Git",
    fullName: "Git & GitHub Desktop",
    marqueeName: "Git / GitHub",
    subname: "Branching Architecture, Merge Resolution, Semantic Releases",
    category: "DevOps & Tooling",
    brandColor: "#F97316",
    glowColor: "rgba(249, 115, 22, 0.35)",
    tag: "Version Control",
    badgeStyle: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    logoUrl: "/assets/img/logo/githubdesktop.png",
    iconType: "git",
    experience: "4+ Years",
    proficiency: 96,
    highlights: [
      "Feature branching, GitFlow strategies & atomic commit hygiene",
      "Conflict-free merging across multi-developer sprints and client releases",
      "GitHub Actions CI/CD workflows for linting, testing, and deployment",
    ],
    benchmark: "Maintained clean version histories across 10+ codebases",
    stackTier: "Infrastructure & Runtime",
    inShowroomCard: true,
  },
  {
    id: "etl-data",
    name: "ETL Data",
    shortName: "ETL Data",
    fullName: "ETL Data (Talend, Apache HOP)",
    marqueeName: "ETL (Talend, Apache HOP)",
    subname: "Automated Extraction, Transform & Load Pipelines with Talend and Apache HOP",
    category: "DevOps & Tooling",
    brandColor: "#FF5D5D",
    glowColor: "rgba(255, 93, 93, 0.4)",
    tag: "Data Pipelines",
    badgeStyle: "bg-rose-500/15 text-rose-300 border-rose-500/30",
    iconType: "etl",
    experience: "2+ Years",
    proficiency: 91,
    highlights: [
      "Talend automated data transformation & multi-source database migration jobs",
      "Apache HOP metadata-driven visual workflow design & pipeline orchestration",
      "Automated scheduled batch extraction, cleansing, and loading into analytics databases",
    ],
    benchmark: "Automated recurring ETL batch pipelines with zero data drift",
    stackTier: "Infrastructure & Runtime",
    inShowroomCard: true,
  },
  {
    id: "docker-vbox",
    name: "Docker & VirtualBox",
    shortName: "Docker",
    fullName: "Docker & VirtualBox",
    marqueeName: "Docker / VBox",
    subname: "Containerization, Multi-Stage Builds, Isolated Headless VMs",
    category: "DevOps & Tooling",
    brandColor: "#0284C7",
    glowColor: "rgba(2, 132, 199, 0.35)",
    tag: "Containerization",
    badgeStyle: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    logoUrl: "/assets/img/logo/virtualbox.png",
    iconType: "docker",
    experience: "3+ Years",
    proficiency: 90,
    highlights: [
      "Multi-container docker compose stacks (Nginx, PHP-FPM 8.3, MySQL, Redis)",
      "Strict local-to-production parity eliminating deployment divergence",
      "Headless virtual machine orchestration for client staging replicas",
    ],
    benchmark: "Reproducible container stacks configured for rapid onboarding",
    stackTier: "Infrastructure & Runtime",
    inShowroomCard: true,
  },
  {
    id: "laragon-homestead",
    name: "Laragon & Homestead",
    shortName: "Laragon",
    fullName: "Laragon & Homestead (PHP 7.0 - 8.3)",
    marqueeName: "Laragon / Homestead",
    subname: "Windows & Ubuntu Multi-PHP Environments (PHP 7.0 to 8.3)",
    category: "DevOps & Tooling",
    brandColor: "#06B6D4",
    glowColor: "rgba(6, 182, 212, 0.35)",
    tag: "Dev Environment",
    badgeStyle: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    logoUrl: "/assets/img/logo/laragon.png",
    iconType: "laragon",
    experience: "4+ Years",
    proficiency: 97,
    highlights: [
      "Fast switching between legacy PHP 7.0 and modern PHP 8.3 with zero downtime",
      "Automated Nginx SSL virtual host provisioning for test domains",
      "Vagrant Homestead headless VM development with synced folders",
    ],
    benchmark: "Instantaneous local development with zero port conflicts",
    stackTier: "Infrastructure & Runtime",
    inShowroomCard: true,
  },
  {
    id: "linux-systems",
    name: "Linux Systems",
    shortName: "Linux",
    fullName: "Linux Systems (Ubuntu / Debian / CentOS)",
    marqueeName: "Linux (Ubuntu/Debian)",
    subname: "CLI Server Administration, Systemd Services, Supervisor & Nginx",
    category: "DevOps & Tooling",
    brandColor: "#F59E0B",
    glowColor: "rgba(245, 158, 11, 0.35)",
    tag: "Server Admin",
    badgeStyle: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    logoUrl: "/assets/img/logo/linux.png",
    iconType: "linux",
    experience: "4+ Years",
    proficiency: 93,
    highlights: [
      "Production VPS setup, firewall policies (UFW/fail2ban) & SSH security",
      "Supervisord configuration for continuous background queue workers",
      "Cron job schedules, log rotation & automated daily database backup scripts",
    ],
    benchmark: "High-uptime production hosting across cloud VPS instances",
    stackTier: "Infrastructure & Runtime",
    inShowroomCard: true,
  },

  // ==========================================
  // 4. AI & AUTONOMOUS WORKFLOWS
  // ==========================================
  {
    id: "antigravity",
    name: "Antigravity",
    shortName: "Antigravity",
    fullName: "Google Antigravity AI Assistant",
    marqueeName: "Antigravity AI",
    subname: "Advanced Agentic AI Assistant, Multi-Agent Orchestration & Autonomous Coding",
    category: "AI & Autonomous Tooling",
    brandColor: "#00F5FF",
    glowColor: "rgba(0, 245, 255, 0.4)",
    tag: "Agentic AI",
    badgeStyle: "bg-cyan-500/15 text-cyan-300 border-cyan-500/30",
    iconType: "antigravity",
    experience: "2+ Years",
    proficiency: 98,
    highlights: [
      "Advanced agentic coding & multi-subagent autonomous task decomposition",
      "Zero-drift context engineering across large production codebases",
      "Rapid end-to-end prototyping and architectural modernization",
    ],
    benchmark: "Multiplies feature shipping velocity by 3x with high rigor",
    stackTier: "AI Intelligence",
    inShowroomCard: true,
  },
  {
    id: "claude-code",
    name: "Claude Code",
    shortName: "Claude Code",
    fullName: "Claude Code (Autonomous CLI Agent)",
    marqueeName: "Claude Code",
    subname: "Autonomous Terminal CLI Agent, Deep Multi-File Refactoring & Context Synthesis",
    category: "AI & Autonomous Tooling",
    brandColor: "#D97757",
    glowColor: "rgba(217, 119, 87, 0.4)",
    tag: "CLI Agent",
    badgeStyle: "bg-orange-500/15 text-orange-300 border-orange-500/30",
    iconType: "claude",
    experience: "2+ Years",
    proficiency: 97,
    highlights: [
      "Terminal-native autonomous refactoring preserving all types and comments",
      "Deep semantic search and automated dependency graph traversal",
      "Context-engineered prompt workflows and multi-agent coordination",
    ],
    benchmark: "Autonomous CLI agent for complex fullstack refactors",
    stackTier: "AI Intelligence",
    inShowroomCard: true,
  },
  {
    id: "deepseek-qwen",
    name: "DeepSeek",
    shortName: "DeepSeek",
    fullName: "DeepSeek 4.1 & Qwen 3.8 Flash",
    marqueeName: "DeepSeek 4.1",
    subname: "Deep Algorithmic Reasoning, AST Parsing, Code Synthesis & Architectural Review",
    category: "AI & Autonomous Tooling",
    brandColor: "#1D72F3",
    glowColor: "rgba(29, 114, 243, 0.4)",
    tag: "Deep Reasoning",
    badgeStyle: "bg-blue-500/15 text-blue-300 border-blue-500/30",
    iconType: "deepseek",
    experience: "2+ Years",
    proficiency: 95,
    highlights: [
      "Complex algorithmic verification and multi-file edge-case diagnosis",
      "Automated SQL schema evaluation and query optimization analysis",
      "AST code synthesis for high-throughput backend pipelines",
    ],
    benchmark: "High-reasoning code verification and bug-free logic validation",
    stackTier: "AI Intelligence",
    inShowroomCard: true,
  },
  {
    id: "local-agent",
    name: "Local Agent",
    shortName: "Local Agent",
    fullName: "Local Agent (LM Studio / Pinokio)",
    marqueeName: "Local Agent (LM Studio / Pinokio)",
    subname: "Air-Gapped Autonomous Inference, Quantized GGUF Models & Zero Cloud Leakage",
    category: "AI & Autonomous Tooling",
    brandColor: "#10B981",
    glowColor: "rgba(16, 185, 129, 0.4)",
    tag: "Local Autonomy",
    badgeStyle: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30",
    iconType: "local-agent",
    experience: "2+ Years",
    proficiency: 92,
    highlights: [
      "100% offline local AI inference with zero network telemetry",
      "Quantized 4-bit / 8-bit GGUF model execution on local hardware",
      "Strict confidentiality preservation for sensitive enterprise logic and data",
    ],
    benchmark: "Zero cloud exposure for confidential business algorithms",
    stackTier: "AI Intelligence",
    inShowroomCard: true,
  },
  {
    id: "on-prem-nvidia",
    name: "On-Prem Nvidia",
    shortName: "Nvidia",
    fullName: "On-Prem Nvidia (CUDA / Tensor)",
    marqueeName: "On-Prem Nvidia",
    subname: "Dedicated Hardware Acceleration, CUDA Cores, TensorRT & High-Speed LLM Inference",
    category: "AI & Autonomous Tooling",
    brandColor: "#76B900",
    glowColor: "rgba(118, 185, 0, 0.4)",
    tag: "Nvidia GPU",
    badgeStyle: "bg-lime-500/15 text-lime-400 border-lime-500/30",
    iconType: "nvidia",
    experience: "2+ Years",
    proficiency: 93,
    highlights: [
      "NVIDIA CUDA & TensorRT acceleration for ultra-fast local LLM token throughput",
      "On-premise GPU workstation configuration for zero-latency developer inference",
      "VRAM allocation optimization for quantized 7B to 70B parameter models",
    ],
    benchmark: "Hardware-accelerated token generation with sub-20ms first-token latency",
    stackTier: "AI Intelligence",
    inShowroomCard: true,
  },
];
